import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import Header from '../src/components/Surfaces/Header'
import Label from '../src/components/Typography/Label'
import MyPlant from '../src/patterns/MyPlant'
import Sale from '../src/patterns/Sale'
import Welcome from '../src/patterns/Welcome'
import Px2vw from '../src/utils/Px2vw'
import styles from '../styles/Home.module.css'

const Body = styled.body`
  height: 100%;        
  width: 100%;
  background-color: #f8f6f6;
  background-position: center top;
  background-size: 100% auto;        
`

const HeaderStyle = styled.div`
  position: relative;
  z-index: 1;
`

const WelcomeStyle = styled.div`
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;        
  margin-inline: ${Px2vw(220)};
`;

const MyPlantStyle = styled.div`
  display: flex;
  align-items: flex-start;
  justify-content: center;        
`;

const SaleStyle = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 40px;
  margin-inline: ${Px2vw(220)};
`;

const Home: NextPage = () => {

  return (
    <Body>
      <HeaderStyle>
        <Header></Header>
      </HeaderStyle>
      <WelcomeStyle>
        <Welcome
          prefixTitle="Sua casa com as"
          title="melhores plantas"
          text="Encontre aqui uma vasta seleção de plantas para decorar a sua casa e torná-lo uma pessoa mais feliz no seu dia a dia. Entre com seu e-mail e assine nossa newsletter para saber das novidades da marca." />
      </WelcomeStyle>
      <MyPlantStyle>
        <MyPlant prefixTitle="Como conseguir" title="minha planta" />
      </MyPlantStyle>
      <SaleStyle>
        <Sale prefixTitle='Conheça nossa' title='Ofertas' />
      </SaleStyle>
    </Body>
  );
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Welcome to <a href="https://nextjs.org">Next.js!</a>
  //       </h1>

  //       <p className={styles.description}>
  //         Get started by editing{' '}
  //         <code className={styles.code}>pages/index.tsx</code>
  //       </p>

  //       <div className={styles.grid}>
  //         <a href="https://nextjs.org/docs" className={styles.card}>
  //           <h2>Documentation &rarr;</h2>
  //           <p>Find in-depth information about Next.js features and API.</p>
  //         </a>

  //         <a href="https://nextjs.org/learn" className={styles.card}>
  //           <h2>Learn &rarr;</h2>
  //           <p>Learn about Next.js in an interactive course with quizzes!</p>
  //         </a>

  //         <a
  //           href="https://github.com/vercel/next.js/tree/canary/examples"
  //           className={styles.card}
  //         >
  //           <h2>Examples &rarr;</h2>
  //           <p>Discover and deploy boilerplate example Next.js projects.</p>
  //         </a>

  //         <a
  //           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //         >
  //           <h2>Deploy &rarr;</h2>
  //           <p>
  //             Instantly deploy your Next.js site to a public URL with Vercel.
  //           </p>
  //         </a>
  //       </div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //   </div>
  // )
}

export default Home
